### ISSUE TITLE
Bug on unregister

### ISSUE THREAD

**Issue by tungle** [square/otto#127]
Already registered my activity at onResume() but still running into this exception when I un-register it at onPause().
However, I'd like to suggest better error handling. If the object is really not registered, why don't Bus just ignore it when there is a call to un-register, instead of throwing an exception and crash the app? 

Caused by: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class com.company.activity.MyActivity registered?
       at com.squareup.otto.Bus.unregister(Bus.java:288)
       at com.company.activity.MyActivity.onPause(SingleTripResultActivity.java:231)
       at android.app.Activity.performPause(Activity.java:5493)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1251)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3171)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3140)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3118)
       at android.app.ActivityThread.access$1000(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5293)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by albaraamishlawi** [comment]
I know I'm late @nkeskinov but can try to call "unregister" in "onPause" before calling the super like the following:

```
@Override
public void onPause() {
    BusProvider.getInstance().unregister(this);
    super.onPause();
}

**Comment by nkeskinov** [comment]
Thanks, I will try it. However, I plan to move to EventBus soon, so I am not sure if I will see the effects, but your suggestion makes sense.

**Comment by adgeg** [comment]
We have exactly the same crash in our application. In our case, the unregistration is properly made before the call to super.onPause(), as @albaraamishlawi has suggested.
For us, this only appears on Samsung devices. And after a quick search, I can see [issues](https://code.google.com/p/android/issues/detail?id=74464#c3) where Activity#onPause() may have been called without Activity#onResume() on those devices...

**Comment by nkeskinov** [comment]
Sorry, I moved to EventBus in meantime. Cannot confirm that the last proposed solution fixes the problem.

**Comment by alexustinovsm** [comment]
+1 the same problem

**Comment by informramiz** [comment]
Try this. 

`public class YourBus extends Bus{
    private ArrayList<Object> registeredObjects = new ArrayList<>();

    @Override
    public void register(Object object) {
        if (!registeredObjects.contains(object)) {
            registeredObjects.add(object);
            super.register(object);
        }
    }

    @Override
    public void unregister(Object object) {
        if (registeredObjects.contains(object)) {
            registeredObjects.remove(object);
            super.unregister(object);
        }
    }
}`

**Comment by informramiz** [comment]
Try subclassing Bus. Something like

```java
public class YourBus extends Bus{
private ArrayList registeredObjects = new ArrayList<>();

@Override
public void register(Object object) {
    if (!registeredObjects.contains(object)) {
        registeredObjects.add(object);
        super.register(object);
    }
}

@Override
public void unregister(Object object) {
    if (registeredObjects.contains(object)) {
        registeredObjects.remove(object);
        super.unregister(object);
    }
}
}
```

**Comment by imminent** [comment]
Would encourage use of a Set if you're going to want to do a contains()
check on it.

**Comment by aleripe** [comment]
Same problem here. Any solution?

**Comment by jackcsk** [comment]
We've seen this issue from time to time on not only Samsung, but also OPPO and Sony devices (as reported by Fabrics), across Android 4 and 5.
We've implemented the register and unregister routine in onStart & onStop respectively since the beginning, so it is obvious that in some cases, onStart() was not called properly. (nope, there is no other call that may interrupt the `register(this)` call in `onStart()`, unless it is from `AppCompatActivity` or its parent class)
We've ended up using try-catch to wrap the exception

**Comment by usmaan-bjss** [comment]
I have just seen a very similar error and it's because of the following: http://stackoverflow.com/questions/40076459/otto-unregistering-the-same-instance

I do not have a fix for this because it makes no sense as to why the unregister function's "this" parameter is the same as the previous object's "this" parameter.

**Comment by usmaanz** [comment]
I have just seen this error occur in a similar set-up. It's a little hard to grasp but please feel free to question if you don't understand:

http://stackoverflow.com/questions/40076459/otto-unregistering-the-same-instance

Essentially, my Activity has a ViewPager and Two Fragments which try to Register and Unregister.

When I close the Activity, it crashes because the FIRST fragment successfully unregisters but when the second fragment tries to unregister, the "this" parameter is for some strange, strange reason, the same reference object as the first one...Which has obviously been unregistered.

Why/how is this even possible?

**Comment by usmaanz** [comment]
Why is there no isRegistered method at least to check if it is registered or not?

**Comment by JakeWharton** [comment]
Because it means you don't really understand your lifecycle.
