### ISSUE TITLE
where to put unregister for regular object?

### ISSUE THREAD

**Issue by pcompassion** [square/otto#129]
for activity/thread, we can use onResume / onPause

What if we want to register/unregister in a regular object class which doesn't have notion of destructor or getting killed...

**Comment by JakeWharton** [comment]
The fact that you want to unregister a regular object means that it's fundamentally tied to a lifecycle and you should use that lifecycle to dictate unregister. Whether it's an Android lifecycle or a custom one tied to something else (e.g., network connectivity, user logged in, etc.).

Otherwise, you wouldn't be unregistering.
