### ISSUE TITLE
Add Bus.postDelayed(long milliseconds)

### ISSUE THREAD

**Issue by basnopisets** [square/otto#143]
Sometimes it is necessary to post events with some delay. It would be great to do this using Otto's features and not to create custom Handlers etc.

**Comment by necronet** [comment]
Can you provide an example where you would need a delay?

**Comment by basnopisets** [comment]
Sure. I have an activity hosting fragment with viewpager also hosting fragments in which I have list of items. Clicking on item I need to open new detail activity and I doing it using startActivityForResult in my activity. So when I come back from new activity result from new activity comes to calling activity, not to fragment and I am using Otto to post event with this result to the nested fragment. But If I post event without delay I get a NPE, cause fields in fragment not restored at that time. So I post event with small delay (round 5 ms) to avoid this NPE.

**Comment by JakeWharton** [comment]
You are describing a race condition and simply delaying by an arbitrary amount is not a safe fix. If the main thread handler has many messages to process, 5ms might not always be enough. The correct way to fix this is to either just post a `Runnable` to the main thread after the fragment transaction has happened (this will ensure the event fires after the fragments have been initialized) or simply to use another mechanism instead of an event bus that isn't prone to data loss.

An event bus, by nature, is a means of broadcasting information to anyone who is listening. If you can't handle data loss by missed events, perhaps a more traditional listener pattern would be more appropriate.
