### ISSUE TITLE
Bus Posting With Class Exclusions

### ISSUE THREAD

**Issue by clackbib** [square/otto#153]
It can sometimes happen that I need to post an event that a class usually listens to, but that I don't want being picked up for a specific post of the same event type .
Would this be a valid use case for otto?
```java
 void post(Object event, Class ... exclusions)
```
I have a commit for a quick idea of what it would look like. If approved, I'll re-fork for cleanliness, implement it and make a pull request.
14e71148ad74bd8221b7259884e1349f75b5f426

**Comment by JakeWharton** [comment]
This results in a strange coupling between the event publishing site and the subscribers. The purpose of a bus is to decouple the two but this API requires that a publisher know about specific subscribers types.

In addition to that, I see two additional problems with this API:
 * It does not have any means to differentiate two instances of of the same type so that only one received an event.
 * Its presence would open up the door for all kinds of additional types of filtering requests for APIs.

For an event bus which is supposed to simply exist as a central hub of message passing, the best way to filter is to have the subscriber decide whether or not it wants to react to an event based on some conditional. This is infinitely scalable and adaptable to whatever requirements an individual app has vs. the limit nature of filtering here.
