### ISSUE TITLE
Weak references for observers/subscribers

### ISSUE THREAD

**Issue by ultraon** [square/otto#168]
Hello, Bus uses non weak references for storing subscribers, and in some case we can't make unregister subscriber. It can be memory leak. What about weak references implementation for Bus?

**Comment by JakeWharton** [comment]
We explored this and determined it was an anti-pattern. If you need to unregister an object there will always be some signal that it should be done. Otherwise the object can just remain subscribed for the lifetime of the process. You can even fire an event on the bus to inform objects to unregister as a decoupling mechanism if they are far removed from the lifecycle.
