### ISSUE TITLE
Check if object is already registered

### ISSUE THREAD

**Issue by rtoshiro** [square/otto#169]
Are there any easy way to check if object is already registered?

**Comment by JakeWharton** [comment]
No. Why do you need such an API?

**Comment by rtoshiro** [comment]
Well, just because I was unregistering my objects using activity/fragment life cycles and I wanted not to worry about registering calls.

**Comment by JakeWharton** [comment]
If you use matching lifecycle callbacks for registration there should be no need to defensively check against registration. Since Otto is instance-based, if you are truly worried about registering twice (because you are not using matching lifecycle callbacks) you can keep your own 'registered' boolean in the instance.

We spent a lot of time evaluating the need for a method which checks very early on (and now a few years ago), and it was determined that this is defensive check was an anti-pattern. The need to check if an object is registered was a defensive call that was always the result of a bug in handling registration, rather than something actually being registered twice legitimately. And in that rare case, as I said above, you can maintain your own flag.

**Comment by rtoshiro** [comment]
Sure, I agree with you. It was just a lack of love about a code I'm testing. Thank you anyway for your answer and time.
