### ISSUE TITLE
Registering an parent class does not work

### ISSUE THREAD

**Issue by mr-thierry** [square/otto#26]
I have a parent activity that contains a `@Subscribe` method. When I try to register the parent using `bus.register(this)`, the `AnnotatedHandlerFinder` finds all `@Subscribe` methods in the child class, not in the parent. 

That's because:
`AnnotatedHandlerFinder.findAllSubscribers()` take the class of the instance and not the parent.

A solution would be to add a new method `bus.register(this, listenerClass)`, where `listenerClass`is the type of the parent object?

**Comment by Niades** [comment]
Although there is a shortcoming to @gmale 's approach: the parent class must contain every possible event handler that it's ancestors might have, because otherwise they would have nothing to override and if they use `@Subscribe`, they simply won't get notified of any events because their instances are not registered in the bus, only the listener object is.
