### ISSUE TITLE
Various questions 

### ISSUE THREAD

**Issue by glenviewjeff** [square/otto#27]
I just learned about Otto--I use Guava's EventBus with RoboGuice extensively.  First, I'm not sure where a good place is to ask questions like this.. A Google group might be excessive, and it seems too specialized for Stack Overflow.

It's not clear to me what the purpose is of the `@Produce` feature.  I guess it's a convenience annotation that automatically posts the return value at registration time?  If my understanding is correct, consider changing the documentation to call this out explicitly?  I didn't understand it until writing this question and re-parsing it several times.

**Comment by meierjan** [comment]
I had the same questions and the documentation is still not clear here. Especially for this:
> Typically you would register a @Produce method in something more long-lived than an activity as well (e.g., a service that is constantly listening for location updates and keeping track of the latest). You can also use things like singletons for this that are always on the bus.

**Comment by clay-to-n** [comment]
@meierjan imagine the case where your app has multiple Activities and Fragments that require a recent location to work (maybe for a game about finding and collection fictional creatures).  You have some background LocationManager service that is posting Otto events whenever the location updates.  The Fragments and Activities subscribe to these events.

Here's a timeline of that service posting these events, where each (*) is a location event:
-----(*)-----(*)---------(*)---------(A)-----------(*)------------------(*)---------

What happens if you start a new FragmentA at that (A) location?  There would be a time-gap between when the Fragment is initialized (and registered to the bus), and when it receives it's first location event.

You could get around this (using Otto) by having FragmentA post some NeedsLocation event, and having the LocationManager respond by posting a location update event.

But if you use the Provides annotation on the LocationManager, as soon as FragmentA is registered to the bus, it will receive the last posted location, without having to explicitly ask the LocationManager to send it the last known location..

**Comment by meierjan** [comment]
> maybe for a game about finding and collection fictional creatures
Are we talking about Pokemons? 👍
